import { Urbanist, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/Footer";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Swiper CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
        />

        {/* ✅ Swiper JS */}
        <script
          src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"
          defer
        ></script>
      </head>

      <body
        className={`${urbanist.variable} ${inter.variable} antialiased bg-black text-white`}
      >
        {/* Header */}
        <div className="max-w-[850px] mx-auto mt-10 px-5 relative z-50">
          <Header />
        </div>

        {/* Page Content */}
        {children}

        {/* Footer */}
        <div className="w-full bg-[#262626] mx-auto mt-10 px-5 relative z-50">
          <Footer />
        </div>
      </body>
    </html>
  );
}
